# .reviewer-config.sh — claude-code-reviewer configuration
# Generated by install.sh on 2026-04-11
# Edit to match your project. Source: https://github.com/jazzsequence/claude-code-reviewer

REVIEWER_TEST_CMD="composer test:unit"
REVIEWER_LINT_CMD="composer lint"
REVIEWER_BUILD_CMD="composer analyse:phpstan"
REVIEWER_E2E_CMD=""

REVIEWER_MAX_FILES=10
REVIEWER_MAX_INSERTIONS=1000
# 1800s: agent round-trip latency in long sessions exceeded the old 300s
# window (observed 19-21 min between flag write and commit on 2026-06-12).
REVIEWER_APPROVAL_TIMEOUT=1800
REVIEWER_APPROVAL_FILE="reviewer-approved"

REVIEWER_TEXT_ONLY_PATTERN='\.(md|txt|rst)$'
REVIEWER_EXCLUDED_FILES='^package-lock\.json$|^yarn\.lock$|^pnpm-lock\.yaml$|^composer\.lock$|^Gemfile\.lock$'
