# .reviewer-config.sh — claude-code-reviewer configuration
# Generated by install.sh on 2026-04-11
# Edit to match your project. Source: https://github.com/jazzsequence/claude-code-reviewer

REVIEWER_TEST_CMD="composer test:unit"
REVIEWER_LINT_CMD="composer lint"
REVIEWER_BUILD_CMD="composer analyse:phpstan"
REVIEWER_E2E_CMD=""

REVIEWER_MAX_FILES=10
REVIEWER_MAX_INSERTIONS=1000
# Widened from 300 on 2026-06-10 (user-approved): reviewer-agent round-trip
# latency in long sessions runs 300-900s, structurally exceeding the old window.
REVIEWER_APPROVAL_TIMEOUT=1200
REVIEWER_APPROVAL_FILE="reviewer-approved"

REVIEWER_TEXT_ONLY_PATTERN='\.(md|txt|rst)$'
REVIEWER_EXCLUDED_FILES='^package-lock\.json$|^yarn\.lock$|^pnpm-lock\.yaml$|^composer\.lock$|^Gemfile\.lock$'
